package ru.SelSup.CrptApi.model.enums;

public enum TypeDoc {
    AGGREGATION_DOCUMENT, AGGREGATION_DOCUMENT_CSV, AGGREGATION_DOCUMENT_XML, DISAGGREGATION_DOCUMENT,
    DISAGGREGATION_DOCUMENT_CSV, DISAGGREGATION_DOCUMENT_XML, REAGGREGATION_DOCUMENT, REAGGREGATION_DOCUMENT_CSV,
    REAGGREGATION_DOCUMENT_XML, LP_INTRODUCE_GOODS, LP_SHIP_GOODS, LP_SHIP_GOODS_CSV, LP_SHIP_GOODS_XML,
    LP_INTRODUCE_GOODS_CSV, LP_INTRODUCE_GOODS_XML, LP_ACCEPT_GOODS, LP_ACCEPT_GOODS_XML, LK_REMARK, LK_REMARK_CSV,
    LK_REMARK_XML, LK_RECEIPT, LK_RECEIPT_XML, LK_RECEIPT_CSV, LP_GOODS_IMPORT, LP_GOODS_IMPORT_CSV
}
